version: '3'

services:
    mariadoura:
        image: mariadb
        container_name: mariadoura
        environment:
            MARIADB_ROOT_PASSWORD: dourabot123
            MARIADB_DATABASE: master
            MARIADB_USER: dourabot
            MARIADB_PASSWORD: davide123
        networks:
            - douranetwork
        # volumes:
        #     - ./mariadb:/var/lib/mariadb

    dourabot:
        image: davide2707clemente/dourabot:1.0
        container_name: dourabot
        environment:
            DB_HOST: mariadoura
            DB_USER: root
            DB_PASSWORD: 'davide123'
            DB_DATABASE: master
        networks:
            - douranetwork
        links:
            - 'mariadoura'
networks:
    douranetwork:
        driver: bridge
        name: douranetwork
