version: '3'

networks:
    douranetwork:
        driver: bridge
        ipam:
            config:
                - subnet: '172.22.0.0/16'

services:
    mariadoura:
        image: mariadb:latest
        container_name: mariadoura
        networks:
            - douranetwork
        ports:
            - '3306:3306'
        env_file: .env
        volumes:
            - ./mariadb:/var/lib/mysql
        restart: always

    dourabot:
        depends_on:
            - mariadoura
        image: davide2707clemente/dourabot:latest
        container_name: dourabot
        networks:
            - douranetwork
        env_file: .env
        restart: on-failure

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 300 --cleanup dourabot
