CREATE table if not exists BIRTHDAYS(
    USER_ID BIGINT NOT NULL PRIMARY KEY ,
    USERNAME varchar(200) NOT NULL,
    BIRTH_DATE varchar(20) NOT NULL
);

CREATE TABLE if not exists BIRTHDAY_MESSAGES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE VARCHAR(2000)
);

CREATE TABLE if not exists CARDS(
    ID VARCHAR(200) PRIMARY KEY,
    GAME VARCHAR(100),
    image BLOB
);

CREATE TABLE IF NOT EXISTS PERSISTENT_MESSAGES(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EVENT VARCHAR(2000)
);



